### ISSUE TITLE
Replace touch and mouse events with pointer events

### ISSUE THREAD

**Issue by nerdyman** [nerdyman/react-compare-slider#74]
The library currently uses `mouse` _and_ `touch` event bindings from V1 when IE11 was supported. All currently targeted browsers support `pointer` events so they should be used instead.

See https://github.com/nerdyman/react-compare-slider/commit/5c84c5c7334dd2724d12a4c6e0eba043dd6aa687 ([full file here](https://github.com/nerdyman/react-compare-slider/blob/5c84c5c7334dd2724d12a4c6e0eba043dd6aa687/src/ReactCompareSlider.tsx)) for a reference implementation.

## Requirements

- [x] Add  `touchAction: 'none'` style property to root element
- [x] Replace `mousedown` event binding with `pointerdown`
- [x] Remove `touchstart` event binding
- [x] Update mouse and touch handlers to replace `MouseEvent | TouchEvent` with `PointerEvent` 
- [x] Remove `instanceof` ternaries in mouse and touch handlers, we can use `ev.pageX` and `ev.pageY`

### Testing

- [ ] Test on iOS Safari
- [ ] Test on iOS Chrome
- [x] Test on Firefox Android
- [x] Test on Android Chrome
- [x] Test on Desktop Safari
- [x] Test on Desktop Chrome
- [x] Test on Desktop Firefox 

## TODO

- [x] Safari desktop - Investigate and fix [laggy change position on hover issue](https://deploy-preview-94--react-compare-slider.netlify.app/iframe.html?args=&id=demos--change-position-on-hover) - caused by CSS filters on those demos
- [x] Safari desktop - Investigate and fix [laggy only handle draggable issue](https://deploy-preview-94--react-compare-slider.netlify.app/iframe.html?args=&id=demos--only-handle-draggable&viewMode=story) - caused by CSS filters on those demos

**Comment by muditchoudhary** [comment]
hey @nerdyman I would like to work on this. But could you describe a more like
 What are the files where I need to replace touch/mouse events with a pointer?

**Comment by nerdyman** [comment]
Hey @muditchoudhary! I've updated the ticket to include a link to a reference implementation and have added some requirements. I still need to do #87 before any Hacktoberfest tickets can be merged, I'll be sorting it out later today.

**Comment by muditchoudhary** [comment]
okay, No issue.

**Comment by nerdyman** [comment]
This is ready to tackle @muditchoudhary , let me know if you need any more info.

**Comment by muditchoudhary** [comment]
> This is ready to tackle @muditchoudhary, let me know if you need any more info.

okay, that's awesome, I'll start working today If I need any help I'll surely reach you.
Thanks!!

**Comment by muditchoudhary** [comment]
Hello, @nerdyman I'm getting this error when I replace MouseEvent | TouchEvent with PointerEvent :

![image](https://user-images.githubusercontent.com/74391865/194206985-90826ae1-4246-4d96-beed-13f4567cc26e.png)

But If I Put it like this `function moveCall(ev: PointerEvent | MouseEvent) {` the error has gone. So what should I do? should I put both PointerEvent & MouseEvent?

**Comment by muditchoudhary** [comment]
One more thing, where will I find the `touchAction: 'none'` property? I did not see any style file and I've also checked other files where I could find this. can you please tell me in which file do I need to check this?

**Comment by nerdyman** [comment]
@muditchoudhary Those events need removed/replaced with `pointerup` and `pointermove` events. I've updated the description for this issue to include links to the full file and also to the previously closed PR. Note that the linked PR also includes a new `transition` feature, that feature is not part of this ticket, just the pointer events changes listed in the description of this issue.

[Here's a link to the diff for the pointer events in that PR](https://github.com/nerdyman/react-compare-slider/pull/67/files#diff-7181b761230f1edfe3e8b6b9c2607b13cd5dafbf5ba6711ffd831bb48304a811L260). The styles for the root element are in [`rootStyles` in the main component](https://github.com/nerdyman/react-compare-slider/pull/67/files#diff-7181b761230f1edfe3e8b6b9c2607b13cd5dafbf5ba6711ffd831bb48304a811L318).

[The linked PR](https://github.com/nerdyman/react-compare-slider/pull/67/files) should have everything needed to check the requirements for this PR. This isn't the simplest issue so if you'd like something else for Hacktoberfest #75 is also open.

**Comment by muditchoudhary** [comment]
@nerdyman If this issue requires the work of just replacing the events in the code I could do that. I'll try to fix this issue with the help of your PR. If I will not able to do it I'll tell you.
